In [31]:
import pandas as pd
import re
from tqdm import tqdm

In [22]:
columns = ['target', 'ids', 'date', 'flag', 'user', 'text']
df = pd.read_csv("Twitter_data.csv", encoding='latin1', names=columns)

In [23]:
df.shape

(1600000, 6)

In [24]:
df.head()

,target,ids,date,flag,user,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."

In [25]:
df = df.drop(['ids', 'date', 'flag', 'user'], axis=1)

In [26]:
df.head()

   target                                               text
0       0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1       0  is upset that he can't update his Facebook by ...
2       0  @Kenichan I dived many times for the ball. Man...
3       0    my whole body feels itchy and like its on fire
4       0  @nationwideclass no, it's not behaving at all....

In [27]:
df["target"].value_counts()

target
0    800000
4    800000
Name: count, dtype: int64

In [28]:
df['target'] = df['target'].replace(4, 1)

In [29]:
df["target"].value_counts()

target
0    800000
1    800000
Name: count, dtype: int64

In [30]:
def preprocess_text(text):
    text = str(text)
    text = re.sub(r'http\S+|www\S+', '', text)
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'\s+', ' ', text)
    
    return text.strip()

In [33]:
tqdm.pandas()
df['cleaned_text'] = df['text'].apply(preprocess_text)

In [35]:
df.head()

,target,text,cleaned_text
0,0,"@switchfoot http://twitpic.com/2y1zl - Awww, t...",- A that's a bummer. You shoulda got David Car...
1,0,is upset that he can't update his Facebook by ...,is upset that he can't update his Facebook by ...
2,0,@Kenichan I dived many times for the ball. Man...,I dived many times for the ball. Managed to sa...
3,0,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
4,0,"@nationwideclass no, it's not behaving at all....","no, it's not behaving at all. i'm mad. why am ..."

In [36]:
df.to_csv("cleaned_twitter_data_bert.csv", index=False)
print("Save successfully!")

Save successfully!